adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    # path('users/read/', adminapp.users, name='user_read'),
    path('users/read/', adminapp.UserListView.as_view(), name='user_read'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='category_read'),
    # path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    # path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    # path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', mainapp.contact, name='contact'),

    path('admin/', include('adminapp.urls', namespace='admin')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms

from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''



adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from adminapp.forms import ShopUserAdminEditForm, ProductEditForm, ProductCategoryEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = 'пользователи/создание'

    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:user_read'))
    else:
        user_form = ShopUserRegisterForm()
    content = {
        'title': title,
        'form': user_form
    }
    return render(request, 'adminapp/user_update.html', content)


# @user_passes_test(lambda u: u.is_superuser)
# def users(request):
#     title = 'админка/пользователи'
#
#     users_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')
#
#     content = {
#         'title': title,
#         'objects': users_list
#     }
#     return render(request, 'adminapp/users.html', content)

# переписываем users
class UserListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'пользователи/редактирование'

    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        user_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:user_read'))
    else:
        user_form = ShopUserAdminEditForm(instance=edit_user)

    content = {
        'title': title,
        'form': user_form
    }
    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'пользователи/удаление'

    user_item = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        if user_item.is_active:
            user_item.is_active = False
        else:
            user_item.is_active = True
        user_item.save()
        return HttpResponseRedirect(reverse('admin:user_read'))

    content = {
        'title': title,
        'user_to_delete': user_item
    }
    return render(request, 'adminapp/user_delete.html', content)


# @user_passes_test(lambda u: u.is_superuser)
# def category_create(request):
#     title = 'категории/создание'
#
#     if request.method == 'POST':
#         category_form = ProductCategoryEditForm(request.POST, request.FILES)
#         if category_form.is_valid():
#             category_form.save()
#             return HttpResponseRedirect(reverse('admin:category_read'))
#     else:
#         category_form = ProductCategoryEditForm()
#     content = {
#         'title': title,
#         'form': category_form
#     }
#     return render(request, 'adminapp/category_update.html', content)


# переписываем category_create
class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('adminapp:category_read')
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'админка/категории'

    categories_list = ProductCategory.objects.all().order_by('-is_active')

    content = {
        'title': title,
        'objects': categories_list
    }
    return render(request, 'adminapp/categories.html', content)


# @user_passes_test(lambda u: u.is_superuser)
# def category_update(request, pk):
#     title = 'категории/редактирование'
#
#     edit_category = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         update_form = ProductCategoryEditForm(request.POST, request.FILES, instance=edit_category)
#         if update_form.is_valid():
#             update_form.save()
#             return HttpResponseRedirect(reverse('admin:category_read'))
#     else:
#         update_form = ProductCategoryEditForm(instance=edit_category)
#
#     content = {
#         'title': title,
#         'form': update_form,
#     }
#
#     return render(request, 'adminapp/category_update.html', content)


# переписываем category_update
class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('adminapp:category_read')
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


# @user_passes_test(lambda u: u.is_superuser)
# def category_delete(request, pk):
#     title = 'категории/удаление'
#
#     category_item = get_object_or_404(ProductCategory, pk=pk)
#     if request.method == 'POST':
#         if category_item.is_active:
#             category_item.is_active = False
#         else:
#             category_item.is_active = True
#         category_item.save()
#         return HttpResponseRedirect(reverse('admin:category_read'))
#
#     content = {
#         'title': title,
#         'category_delete': category_item
#     }
#     return render(request, 'adminapp/category_delete.html', content)


# переписываем category_delete
class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('adminapp:category_read')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()
        return HttpResponseRedirect(self.success_url)

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def product_create(request, pk):
    category_item = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse('admin:products', args=[pk]))
    else:
        product_form = ProductEditForm()

    content = {
        'form': product_form,
        'category': category_item
    }
    return render(request, 'adminapp/product_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = 'админка/пользователи'

    category_item = get_object_or_404(ProductCategory, pk=pk)

    products_list = Product.objects.filter(category__pk=pk).order_by('name')

    content = {
        'title': title,
        'category': category_item,
        'objects': products_list
    }
    return render(request, 'adminapp/products.html', content)


# @user_passes_test(lambda u: u.is_superuser)
# def product_read(request, pk):
#     product_item = get_object_or_404(Product, pk=pk)
#     content = {
#         'object': product_item
#     }
#     return render(request, 'adminapp/product_detail.html', content)


# переписываем product_read
class ProductDetailView(DeleteView):
    model = Product
    template_name = 'adminapp/product_detail.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def product_update(request, pk):
    product_item = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product_form = ProductEditForm(request.POST, request.FILES, instance=product_item)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse('adminapp:products', args=[product_item.category_id]))
    else:
        product_form = ProductEditForm(instance=product_item)

    content = {
        'form': product_form,
        'category': product_item.category
    }

    return render(request, 'adminapp/product_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def product_delete(request, pk):
    product_item = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        if product_item.is_active:
            product_item.is_active = False
        else:
            product_item.is_active = True
        product_item.save()
        return HttpResponseRedirect(reverse('admin:products', args=[product_item.category.pk]))

    content = {
        'product_to_delete': product_item
    }
    return render(request, 'adminapp/product_delete.html', content)

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="admin_container">
    <div class="h2 text-center">
        Админка
    </div>
    {% block menu %}
        <div class="admin_menu">
            {% include 'adminapp/includes/inc_menu.html' %}
        </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
</div>
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="categories_list">
        <button class="new_category">
            <a href={% url 'admin:category_create' %}>
                новая категория
            </a>
        </button>

        {% for object in objects %}
            <div class="category_record
                {% if not object.is_active %}
                    not_active
                {% endif %}">
                <div class="category_name">
                    {{ object.name|title }}
                </div>
                <div class="category_actions">
                    <button>
                        <a href={% url 'admin:products' object.pk %}>
                            товары категории
                        </a>
                    </button>
                    <button>
                        <a href={% url 'admin:category_update' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        {% if object.is_active %}
                            <a href="{% url 'adminapp:category_delete' object.pk %}">удалить</a>
                        {% else %}
                            <a href="{% url 'adminapp:category_delete' object.pk %}">восстановить</a>
                        {% endif %}
                    </button>
                </div>
                <div class="category_desc">
                    {{ object.description|title }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="category_delete">
        Уверены, что хотите
        {% if object.is_active %}
            удалить
        {% else %}
            восстановить
        {% endif %}
        категорию {{ object.name|title }}
        ?
        <form action="{% url 'admin:category_delete' object.pk %}"
              method="post">
            {% csrf_token %}
            {% if object.is_active %}
                <input class="btn btn-danger" type="submit" value="удалить">
            {% else %}
                <input class="btn btn-primary" type="submit" value="восстановить">
            {% endif %}
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:category_read' %}">
                Отмена
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="users_list">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'admin:category_read' %}">
                к списку товаров
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="product_delete">
        Уверены, что хотите
        {% if product_to_delete.is_active %}
            удалить
        {% else %}
            восстановить
        {% endif %}
        продукт {{ product_to_delete.name|title }}?
        <form action="{% url 'admin:product_delete' product_to_delete.pk %}" method="post">
            {% csrf_token %}
            {% if product_to_delete.is_active %}
                <input class="btn btn-danger" type="submit" value="удалить">
            {% else %}
                <input class="btn btn-primary" type="submit" value="восстановить">
            {% endif %}
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:products' product_to_delete.category.pk %}">
                Отмена
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/product_detail.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="product_read">
        <div class="product_name">
            Продукт<strong>{{ object.category.name|title }} /
            {{ object.name|title }}</strong>
        </div>
        <img src="/media/{{ object.image|default:'products_images/default.jpg' }}"
             alt="{{ object.name }}">
        <div class="summary">
            <b>цена</b>
            <p>{{ object.price }} руб</p>
            <b>количество</b>
            <p>{{ object.quantity }}</p>
            <b>в каталоге</b>
            <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
            <p>
                <button>
                    <a href={% url 'admin:product_update' object.pk %}>
                        редактировать
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'admin:product_delete' object.pk %}>
                        удалить
                    </a>
                </button>
            </p>
            <p>
                <button>
                    <a href={% url 'admin:products' object.category.pk %}>
                        назад
                    </a>
                </button>
            </p>
        </div>
        <div class="product_desc">
            <b>краткая информация</b>
            <p>{{ object.short_desc }}</p>
            <br><br>
            <b>подробная информация</b>
            <p>{{ object.description }}</p>
        </div>
    </div>
{% endblock %}


adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="users_list">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'admin:products' category.pk %}">
                к списку товаров
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <div class="products_list">
        <button class="new_product">
            <a href={% url 'adminapp:product_create' category.pk %}>
                новый продукт
            </a>
        </button>

        {% for object in objects %}
            <div class="product_record
                    {% if not object.is_active %}
                        not_active
                    {% endif %}">
{#                <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">#}
                <img src="{{ object.image|media_for_products }}" alt="{{ object.name }}">
                <div class="product_name">
                    {{ object.name|title }}
                </div>
                <div class="product_actions">
                    <button>
                        <a href={% url 'admin:product_read' object.pk %}>
                            подробнее
                        </a>
                    </button>
                    <button>
                        <a href={% url 'admin:product_update' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        {% if object.is_active %}
                            <a href="{% url 'adminapp:product_delete' object.pk %}">удалить</a>
                        {% else %}
                            <a href="{% url 'adminapp:product_delete' object.pk %}">восстановить</a>
                        {% endif %}
                    </button>
                </div>
                <div class="summary">
                    <b>цена</b>
                    <p>{{ object.price }} руб</p>
                    <b>количество</b>
                    <p>{{ object.quantity }}</p>
                </div>
                <div class="product_desc">
                    {{ object.short_desc|title }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="user_delete">
        Уверены, что хотите
        {% if user_to_delete.is_active %}
            удалить
        {% else %}
            восстановить
        {% endif %}
        {{ user_to_delete.username }}
        {% if user_to_delete.first_name %}
            ({{ user_to_delete.first_name|title }})</b>
            {% if user_to_delete.last_name %}
                {{ user_to_delete.last_name|title }}
            {% endif %}
        {% endif %}
        ?
        <form action="{% url 'admin:user_delete' user_to_delete.pk %}"
              method="post">
            {% csrf_token %}
            {% if user_to_delete.is_active %}
                <input class="btn btn-danger" type="submit" value="удалить">
            {% else %}
                <input class="btn btn-primary" type="submit" value="восстановить">
            {% endif %}
        </form>
        <button class="btn btn-success">
            <a href="{% url 'admin:user_read' %}">
                Отмена
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/user_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="users_list">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <button class="btn btn-round form-control last">
            <a href="{% url 'admin:user_read' %}">
                к списку пользователей
            </a>
        </button>
    </div>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <div class="users_list">
        <button>
            <a href="{% url 'adminapp:user_create' %}">новый пользователь</a>
        </button>
        {% for object in object_list %}
            <div class="user_record {% if not object.is_active %}not_active{% endif %}">
{#                <img src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}" alt="{{ object.username }}">#}
                <img src="{{ object.avatar|media_for_users }}" alt="{{ object.username }}">
                <div class="user_role">
                    {% if object.is_superuser %}
                        администратор
                    {% else %}
                        пользователь
                    {% endif %}
                    <button>
                        <a href="{% url 'adminapp:user_update' object.pk %}">редактировать</a>
                    </button>
                    <button>
                        {% if object.is_active %}
                            <a href="{% url 'adminapp:user_delete' object.pk %}">удалить</a>
                        {% else %}
                            <a href="{% url 'adminapp:user_delete' object.pk %}">восстановить</a>
                        {% endif %}
                    </button>
                </div>
            <div class="user_name">
                <p>
                    <strong>{{ object.username }}</strong>
                </p>
                <p>
                    {% if object.first_name %}
                        <b>{{ object.first_name|title }}</b>
                        {% if object.last_name %}
                            <p>{{ object.last_name  }}</p>
                        {% endif %}
                    {% endif %}
                </p>
            </div>
            <div class="user_age">age:<br>{{ object.age }}</div>
            <div class="user_email">email:<br>{{ object.email }}</div>
            <div class="user_lastlogin">logged:<br>{{ object.last_login|date:"d-m-Y" }}</div>
            </div>
        {% endfor %}
    </div>
{% endblock %}