authapp/urls.py
from django.urls import path
from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit')
]

basketapp/urls.py
from django.urls import path
from basketapp import views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>', basketapp.basket_add, name='add'),
    path('remove/<int:pk>', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static

from django.urls import path

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', mainapp.contact, name='contact'),

    path('admin/', include('adminapp.urls', namespace='admin')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='products'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    # path('category/<int:pk>/<int:page>/', mainapp.products, name='page'),
    path('product/<int:pk>', mainapp.product, name='product')
]


mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='имя')
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активность', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, verbose_name='имя')
    image = models.ImageField(upload_to='products_image', blank=True)
    short_desc = models.CharField(max_length=64, verbose_name='краткое описание', blank=True)
    description = models.TextField(blank=True, verbose_name='описание')
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveSmallIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активность', default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

geekshop/mainapp/views.py
from django.shortcuts import render


# Create your views here.
def main(request):
    return render(request, 'mainapp/index.html')


def products(request):
    return render(request, 'mainapp/products.html')


def contact(request):
    return render(request, 'mainapp/contact.html')

mainapp/views.py
import json
import os
from datetime import datetime
import random

from IPython.core.page import page
from django.conf import settings
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

from basketapp.models import Basket
from mainapp.models import Product, ProductCategory


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    return []


def get_hot_product():
    products_list = Product.objects.all()
    return random.sample(list(products_list), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products


def main(request):
    title = 'Главная'

    products = Product.objects.all()[:4]

    content = {
        'title': title,
        'products': products,
        'basket': get_basket(request.user)
    }

    return render(request, 'mainapp/index.html', content)


def products(request, pk=None):
    title = 'Продукты'
    links_menu = ProductCategory.objects.all()

    page = request.GET.get('p', 1)

    if pk is not None:
        if pk == 0:
            products_list = Product.objects.all().order_by('price')
            category_item = {'name': 'все', 'pk': 0}
        else:
            category_item = get_object_or_404(ProductCategory, pk=pk)
            products_list = Product.objects.filter(category__pk=pk).order_by('price')

        paginator = Paginator(products_list, 2)

        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category_item,
            'products': products_paginator,
            'basket': get_basket(request.user)
        }
        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)
    # same_products = Product.objects.all()[:4]

    content = {
        'title': title,
        'links_menu': links_menu,
        'same_products': same_products,
        'hot_product': hot_product,
        'special_offer': datetime.now(),
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    content = {
        'title': 'продукт',
        'product': get_object_or_404(Product, pk=pk),
        'links_menu': ProductCategory.objects.all(),
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/product.html', content)


def contact(request):
    title = 'Контакты'
    locations = []
    with open(os.path.join(settings.BASE_DIR, 'contacts.json'), encoding='utf-8') as f:
        locations = json.load(f)

    content = {
        'title': title,
        'locations': locations,
        'basket': get_basket(request.user)
    }
    return render(request, 'mainapp/contact.html', content)

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>
        Мой магазин | {% if title %}{{ title|title}} {% endif %} | {%  now 'Y' %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
</head>
<body>
<div class="container">
    {% block content %}
    {% endblock %}
</div>

{% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}
</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div class="hero">
        <div class="header clearfix">
            <a href="{% url 'main' %}" class="logo"></a>
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
        <h1>наши контакты</h1>
    </div>

    <div class="location">
        {% for location in locations %}
            <div class="location-1">
                <i class="fa fa-map-marker fa-5x"></i>
                <h4>{{ location.city }}</h4>
                <div class="contacts">
                    <h5>Телефон</h5>
                    <p>{{ location.phone }}</p>
                </div>
                <div class="contacts">
                    <h5>Email</h5>
                    <p>{{ location.email }}</p>
                </div>
                <div class="contacts">
                    <h5>Адрес</h5>
                    <p>{{ location.address }}</p>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div class="slider">
        <div class="header clearfix">
            <a href="{% url 'main' %}" class="logo"></a>
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>

    <div class="featured">
        <div class="featured-menu">
            <a class="active" href="#">Популярные</a><a href="{% url 'products:products' %}">Новинки</a>
        </div>
        <a class="explore" href="{% url 'products:category' 0 %}">показать все <img src="{% static 'img/arrow.png' %}"
                                                                                    alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            {% for product in products %}
                <div class="block">
                    <a href="{% url 'products:product' product.pk %}"><img src="/media/{{ product.image }}" alt="{{ product.name }}">

                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="{{ product.name }}">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.desc }} </p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <div class="hero-white">
        <div class="header clearfix">
            <a href="{% url 'main' %}" class="logo"></a>
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu_product.html' %}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{{ product.image|media_for_products }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="{{ product.image|media_for_products }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{{ product.image|media_for_products }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{{ product.image|media_for_products }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <h3 class="red">{{ product.category.name }}</h3>
                <p class="price"> {{ product.price|floatformat:1 }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>
                        {{ product.description }}
                    </p>
                </div>
            </div>
        </div>
    </div>


    <div class="clr-contact"></div>

{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <div class="hero-white">
        <div class="header clearfix">
            <a href="{% url 'main' %}" class="logo"></a>
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{{ hot_product.image|media_for_products }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image|media_for_products }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image|media_for_products }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image|media_for_products }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="red">Цена действительна до {{ special_offer|date:'d.m' }}</h3>
                <h3 class="big-bold">{{ hot_product.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ hot_product.price|floatformat:1 }} <span>руб</span></p>
                <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>
                        {{ hot_product.description }}
                    </p>
                </div>
            </div>
        </div>

        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="{% url 'products:category' 0 %}">показать все <img
                        src="{% static 'img/arrow.png' %}" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for product in same_products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}"><img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="img">
                                <h3>Категория:{{ product.category.name }}</h3>
                                <h4>Название:{{ product.name }}</h4>
                                <p>Описание:{{ product.description }} </p>
                                <p>Цена:{{ product.price }} </p>
                                <p>На складе:{{ product.quantity }} </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load my_tags %}

{% block content %}
    <div class="hero-white">
        <div class="header clearfix">
            <a href="{% url 'main' %}" class="logo"></a>
            {% include 'mainapp/includes/inc_main_menu.html' %}
        </div>
    </div>

    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_categories_menu.html' %}
        </div>

        <div class="products_list">
            <div class="title clearfix">
                <h2>
                    Категория: "{{ category.name|title }}"
                </h2>
                <div class="paginator">
                    {% if products.has_previous %}
                        <a href="{% url 'products:category' category.pk %}?p={{ products.previous_page_number }}"> < </a>
                    {% endif %}
                    <span class="current">
                        страница {{ products.number }} из {{ products.paginator.num_pages }}
                    </span>
                    {% if products.has_next %}
                        <a href="{% url 'products:category' category.pk %}?p={{ products.next_page_number }}"> > </a>
                    {% endif %}
                </div>
            </div>
            <div class="category-products clearfix">

                {% for product in products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.pk %}">
                            <img src="{{ product.image|media_for_products }}" alt="product">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.description }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}
